# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

# trying to set a cache for images on netlify
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=2678400"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/strategy"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/help"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api-connect"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "dokkanbattlehelper.com/*"
  to = "https://dokkan.team/:splat"
  status = 301
  force = true

[[redirects]]
  from = "www.dokkanbattlehelper.com/*"
  to = "https://dokkan.team/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://dokkanbattlehelper.com/*"
  to = "https://dokkan.team/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404


  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/
