const allCategoryOptions = [
<option value="Accelerated Battle" key="accelerated-battle">Accelerated Battle</option>,
<option value="All-Out Struggle" key="all-out-struggle">All-Out Struggle</option>,
<option value="Androids" key="androids">Androids</option>,
<option value="Androids/Cell Saga" key="androids-cell-saga">Androids/Cell Saga</option>,
<option value="Artificial Life Forms" key="artificial-life-forms">Artificial Life Forms</option>,
<option value="Battle of Fate" key="battle-of-fate">Battle of Fate</option>,
<option value="Battle of Wits" key="battle-of-wits">Battle of Wits</option>,
<option value="Bond of Friendship" key="bond-of-friendship">Bond of Friendship</option>,
<option value="Bond of Master and Disciple" key="bond-of-master-and-disciple">Bond of Master and Disciple</option>,
<option value="Bond of Parent and Child" key="bond-of-parent-and-child">Bond of Parent and Child</option>,
<option value="Connected Hope" key="connected-hope">Connected Hope</option>,
<option value="Corroded Body and Mind" key="corroded-body-and-mind">Corroded Body and Mind</option>,
<option value="Crossover" key="crossover">Crossover</option>,
<option value="DB Saga" key="db-saga">DB Saga</option>,
<option value="Defenders of Justice" key="defenders-of-justice">Defenders of Justice</option>,
<option value="Dragon Ball Heroes" key="dragon-ball-heroes">Dragon Ball Heroes</option>,
<option value="Dragon Ball Seekers" key="dragon-ball-seekers">Dragon Ball Seekers</option>,
<option value="Earth-Bred Fighters" key="earth-bred-fighters">Earth-Bred Fighters</option>,
<option value="Earthlings" key="earthlings">Earthlings</option>,
<option value="Entrusted Will" key="entrusted-will">Entrusted Will</option>,
<option value="Exploding Rage" key="exploding-rage">Exploding Rage</option>,
<option value="Final Trump Card" key="final-trump-card">Final Trump Card</option>,
<option value="Full Power" key="full-power">Full Power</option>,
<option value="Fused Fighters" key="fused-fighters">Fused Fighters</option>,
<option value="Fusion" key="fusion">Fusion</option>,
<option value="Future Saga" key="future-saga">Future Saga</option>,
<option value="GT Bosses" key="gt-bosses">GT Bosses</option>,
<option value="GT Heroes" key="gt-heroes">GT Heroes</option>,
<option value="Giant Ape Power" key="giant-ape-power">Giant Ape Power</option>,
<option value="Giant Form" key="giant-form">Giant Form</option>,
<option value="Gifted Warriors" key="gifted-warriors">Gifted Warriors</option>,
<option value="Ginyu Force" key="ginyu-force">Ginyu Force</option>,
<option value="Goku's Family" key="goku's-family">Goku's Family</option>,
<option value="Heavenly Events" key="heavenly-events">Heavenly Events</option>,
<option value="Hybrid Saiyans" key="hybrid-saiyans">Hybrid Saiyans</option>,
<option value="Inhuman Deeds" key="inhuman-deeds">Inhuman Deeds</option>,
<option value="Joined Forces" key="joined-forces">Joined Forces</option>,
<option value="Kamehameha" key="kamehameha">Kamehameha</option>,
<option value="Legendary Existence" key="legendary-existence">Legendary Existence</option>,
<option value="Low-Class Warrior" key="low-class-warrior">Low-Class Warrior</option>,
<option value="Majin Buu Saga" key="majin-buu-saga">Majin Buu Saga</option>,
<option value="Majin Power" key="majin-power">Majin Power</option>,
<option value="Mastered Evolution" key="mastered-evolution">Mastered Evolution</option>,
<option value="Miraculous Awakening" key="miraculous-awakening">Miraculous Awakening</option>,
<option value="Movie Bosses" key="movie-bosses">Movie Bosses</option>,
<option value="Movie Heroes" key="movie-heroes">Movie Heroes</option>,
<option value="Namekians" key="namekians">Namekians</option>,
<option value="Otherworld Warriors" key="otherworld-warriors">Otherworld Warriors</option>,
<option value="Peppy Gals" key="peppy-gals">Peppy Gals</option>,
<option value="Planet Namek Saga" key="planet-namek-saga">Planet Namek Saga</option>,
<option value="Planetary Destruction" key="planetary-destruction">Planetary Destruction</option>,
<option value="Potara" key="potara">Potara</option>,
<option value="Power Absorption" key="power-absorption">Power Absorption</option>,
<option value="Power Beyond Super Saiyan" key="power-beyond-super-saiyan">Power Beyond Super Saiyan</option>,
<option value="Power of Wishes" key="power-of-wishes">Power of Wishes</option>,
<option value="Powerful Comeback" key="powerful-comeback">Powerful Comeback</option>,
<option value="Pure Saiyans" key="pure-saiyans">Pure Saiyans</option>,
<option value="Rapid Growth" key="rapid-growth">Rapid Growth</option>,
<option value="Realm of Gods" key="realm-of-gods">Realm of Gods</option>,
<option value="Representatives of Universe 7" key="representatives-of-universe-7">Representatives of Universe 7</option>,
<option value="Resurrected Warriors" key="resurrected-warriors">Resurrected Warriors</option>,
<option value="Revenge" key="revenge">Revenge</option>,
<option value="Saiyan Saga" key="saiyan-saga">Saiyan Saga</option>,
<option value="Saviors" key="saviors">Saviors</option>,
<option value="Shadow Dragon Saga" key="shadow-dragon-saga">Shadow Dragon Saga</option>,
<option value="Siblings' Bond" key="siblings'-bond">Siblings' Bond</option>,
<option value="Space-Traveling Warriors" key="space-traveling-warriors">Space-Traveling Warriors</option>,
<option value="Special Pose" key="special-pose">Special Pose</option>,
<option value="Storied Figures" key="storied-figures">Storied Figures</option>,
<option value="Super Heroes" key="super-heroes">Super Heroes</option>,
<option value="Super Saiyan 2" key="super-saiyan-2">Super Saiyan 2</option>,
<option value="Super Saiyan 3" key="super-saiyan-3">Super Saiyan 3</option>,
<option value="Super Saiyans" key="super-saiyans">Super Saiyans</option>,
<option value="Sworn Enemies" key="sworn-enemies">Sworn Enemies</option>,
<option value="Target Goku" key="target-goku">Target Goku</option>,
<option value="Team Bardock" key="team-bardock">Team Bardock</option>,
<option value="Terrifying Conquerors" key="terrifying-conquerors">Terrifying Conquerors</option>,
<option value="Time Limit" key="time-limit">Time Limit</option>,
<option value="Time Travelers" key="time-travelers">Time Travelers</option>,
<option value="Transformation Boost" key="transformation-boost">Transformation Boost</option>,
<option value="Turtle School" key="turtle-school">Turtle School</option>,
<option value="Universe 11" key="universe-11">Universe 11</option>,
<option value="Universe 6" key="universe-6">Universe 6</option>,
<option value="Universe Survival Saga" key="universe-survival-saga">Universe Survival Saga</option>,
<option value="Vegeta's Family" key="vegeta's-family">Vegeta's Family</option>,
<option value="Wicked Bloodline" key="wicked-bloodline">Wicked Bloodline</option>,
<option value="World Tournament" key="world-tournament">World Tournament</option>,
<option value="Worldwide Chaos" key="worldwide-chaos">Worldwide Chaos</option>,
<option value="Worthy Rivals" key="worthy-rivals">Worthy Rivals</option>,
<option value="Youth" key="youth">Youth</option>,

    ];

export default allCategoryOptions