const allCategoryOptions = [
    <option key="all-categories" value="">All Categories</option>,
    <option key="accelerated-battle" value="Accelerated Battle">Accelerated Battle</option>,
    <option key="all-out-struggle" value="All-Out Struggle">All-Out Struggle</option>,
    <option key="androids" value="Androids">Androids</option>,
    <option key="androids-cell-saga" value="Androids/Cell Saga">Androids/Cell Saga</option>,
    <option key="artificial-life-forms" value="Artificial Life Forms">Artificial Life Forms</option>,
    <option key="battle-of-fate" value="Battle of Fate">Battle of Fate</option>,
    <option key="battle-of-wits" value="Battle of Wits">Battle of Wits</option>,
    <option key="bond-of-friendship" value="Bond of Friendship">Bond of Friendship</option>,
    <option key="bond-of-master-and-disciple" value="Bond of Master and Disciple">Bond of Master and Disciple</option>,
    <option key="bond-of-parent-and-child" value="Bond of Parent and Child">Bond of Parent and Child</option>,
    <option key="connected-hope" value="Connected Hope">Connected Hope</option>,
    <option key="corroded-body-and-mind" value="Corroded Body and Mind">Corroded Body and Mind</option>,
    <option key="crossover" value="Crossover">Crossover</option>,
    <option key="db-saga" value="DB Saga">DB Saga</option>,
    <option key="defenders-of-justice" value="Defenders of Justice">Defenders of Justice</option>,
    <option key="dragon-ball-heroes" value="Dragon Ball Heroes">Dragon Ball Heroes</option>,
    <option key="dragon-ball-seekers" value="Dragon Ball Seekers">Dragon Ball Seekers</option>,
    <option key="earthlings" value="Earthlings">Earthlings</option>,
    <option key="entrusted-will" value="Entrusted Will">Entrusted Will</option>,
    <option key="exploding-rage" value="Exploding Rage">Exploding Rage</option>,
    <option key="final-trump-card" value="Final Trump Card">Final Trump Card</option>,
    <option key="full-power" value="Full Power">Full Power</option>,
    <option key="fused-fighters" value="Fused Fighters">Fused Fighters</option>,
    <option key="fusion" value="Fusion">Fusion</option>,
    <option key="future-saga" value="Future Saga">Future Saga</option>,
    <option key="gt-bosses" value="GT Bosses">GT Bosses</option>,
    <option key="gt-heroes" value="GT Heroes">GT Heroes</option>,
    <option key="giant-ape-power" value="Giant Ape Power">Giant Ape Power</option>,
    <option key="giant-form" value="Giant Form">Giant Form</option>,
    <option key="gifted-warriors" value="Gifted Warriors">Gifted Warriors</option>,
    <option key="ginyu-force" value="Ginyu Force">Ginyu Force</option>,
    <option key="goku-family" value="Goku's Family">Goku's Family</option>,
    <option key="heavenly-events" value="Heavenly Events">Heavenly Events</option>,
    <option key="hybrid-saiyans" value="Hybrid Saiyans">Hybrid Saiyans</option>,
    <option key="inhuman-deeds" value="Inhuman Deeds">Inhuman Deeds</option>,
    <option key="joined-forces" value="Joined Forces">Joined Forces</option>,
    <option key="kamehameha" value="Kamehameha">Kamehameha</option>,
    <option key="legendary-challenge" value="Legendary Challenge">Legendary Challenge</option>,
    <option key="majin-buu-saga" value="Majin Buu Saga">Majin Buu Saga</option>,
    <option key="master-of-martial-arts" value="Master of Martial Arts">Master of Martial Arts</option>,
    <option key="mysterious-ritual" value="Mysterious Ritual">Mysterious Ritual</option>,
    <option key="namekians" value="Namekians">Namekians</option>,
    <option key="otherworld-warriors" value="Otherworld Warriors">Otherworld Warriors</option>,
    <option key="peppy-gals" value="Peppy Gals">Peppy Gals</option>,
    <option key="planetary-destruction" value="Planetary Destruction">Planetary Destruction</option>,
    <option key="powerful-opponents" value="Powerful Opponents">Powerful Opponents</option>,
    <option key="prepared-for-battle" value="Prepared for Battle">Prepared for Battle</option>,
    <option key="pure-saiyans" value="Pure Saiyans">Pure Saiyans</option>,
    <option key="realm-of-gods" value="Realm of Gods">Realm of Gods</option>,
    <option key="resurrected-warriors" value="Resurrected Warriors">Resurrected Warriors</option>,
    <option key="revenge" value="Revenge">Revenge</option>,
    <option key="rivals" value="Rivals">Rivals</option>,
    <option key="saviors" value="Saviors">Saviors</option>,
    <option key="shocking-speed" value="Shocking Speed">Shocking Speed</option>,
    <option key="space-traveling-warriors" value="Space-Traveling Warriors">Space-Traveling Warriors</option>,
    <option key="special-pose" value="Special Pose">Special Pose</option>,
    <option key="super-saiyans" value="Super Saiyans">Super Saiyans</option>,
    <option key="target-goku" value="Target: Goku">Target: Goku</option>,
    <option key="time-travelers" value="Time Travelers">Time Travelers</option>,
    <option key="tournament-of-power" value="Tournament of Power">Tournament of Power</option>,
    <option key="universe-6" value="Universe 6">Universe 6</option>,
    <option key="universe-survival-saga" value="Universe Survival Saga">Universe Survival Saga</option>,
    <option key="vengeful-brother" value="Vengeful Brother">Vengeful Brother</option>,
    <option key="wicked-bloodline" value="Wicked Bloodline">Wicked Bloodline</option>,
    <option key="world-tournament" value="World Tournament">World Tournament</option>,
    ];

export default allCategoryOptions