const allCategoryOptions = [
    <option value="">All Categories</option>,
    <option>Accelerated Battle</option>,
    <option>All-Out Struggle</option>,
    <option>Androids</option>,
    <option>Androids/Cell Saga</option>,
    <option>Artificial Life Forms</option>,
    <option>Battle of Fate</option>,
    <option>Battle of Wits</option>,
    <option>Bond of Friendship</option>,
    <option>Bond of Master and Disciple</option>,
    <option>Bond of Parent and Child</option>,
    <option>Connected Hope</option>,
    <option>Corroded Body and Mind</option>,
    <option>Crossover</option>,
    <option>DB Saga</option>,
    <option>Defenders of Justice</option>,
    <option>Dragon Ball Heroes</option>,
    <option>Dragon Ball Seekers</option>,
    <option>Earthlings</option>,
    <option>Entrusted Will</option>,
    <option>Exploding Rage</option>,
    <option>Final Trump Card</option>,
    <option>Full Power</option>,
    <option>Fused Fighters</option>,
    <option>Fusion</option>,
    <option>Future Saga</option>,
    <option>GT Bosses</option>,
    <option>GT Heroes</option>,
    <option>Giant Ape Power</option>,
    <option>Giant Form</option>,
    <option>Gifted Warriors</option>,
    <option>Ginyu Force</option>,
    <option>Goku's Family</option>,
    <option>Heavenly Events</option>,
    <option>Hybrid Saiyans</option>,
    <option>Inhuman Deeds</option>,
    <option>Joined Forces</option>,
    <option>Kamehameha</option>,
    <option>Legendary Existence</option>,
    <option>Low-Class Warrior</option>,
    <option>Majin Buu Saga</option>,
    <option>Majin Power</option>,
    <option>Mastered Evolution</option>,
    <option>Miraculous Awakening</option>,
    <option>Movie Bosses</option>,
    <option>Movie Heroes</option>,
    <option>Namekians</option>,
    <option>Otherworld Warriors</option>,
    <option>Peppy Gals</option>,
    <option>Planet Namek Saga</option>,
    <option>Planetary Destruction</option>,
    <option>Potara</option>,
    <option>Power Absorption</option>,
    <option>Power Beyond Super Saiyan</option>,
    <option>Powerful Comeback</option>,
    <option>Pure Saiyans</option>,
    <option>Rapid Growth</option>,
    <option>Realm of Gods</option>,
    <option>Representatives of Universe 7</option>,
    <option>Resurrected Warriors</option>,
    <option>Revenge</option>,
    <option>Saiyan Saga</option>,
    <option>Saviors</option>,
    <option>Shadow Dragon Saga</option>,
    <option>Siblings' Bond</option>,
    <option>Space-Traveling Warriors</option>,
    <option>Special Pose</option>,
    <option>Storied Figures</option>,
    <option>Super Heroes</option>,
    <option>Super Saiyan 2</option>,
    <option>Super Saiyan 3</option>,
    <option>Super Saiyans</option>,
    <option>Sworn Enemies</option>,
    <option>Target Goku</option>,
    <option>Team Bardock</option>,
    <option>Terrifying Conquerors</option>,
    <option>Time Limit</option>,
    <option>Time Travelers</option>,
    <option>Transformation Boost</option>,
    <option>Turtle School</option>,
    <option>Universe 11</option>,
    <option>Universe 6</option>,
    <option>Universe Survival Saga</option>,
    <option>Vegeta's Family</option>,
    <option>Wicked Bloodline</option>,
    <option>World Tournament</option>,
    <option>Worldwide Chaos</option>,
    <option>Worthy Rivals</option>,
    <option>Youth</option>,
]

export default allCategoryOptions